### ISSUE TITLE
中文目录的 org 不能正常导出，而 latex 直接导出 pdf 是可以在中文目录的

### ISSUE THREAD

**Issue by saccohuo** [tumashu/ox-latex-chinese#2]
如题，在英文目录下的 org 文件是可以正常导出的，但是在中文目录下的 org 文件导出会提示错误。可是，用 org 导出 tex 文件是可以在中文目录的，用 tex 文件直接导出 pdf 也是可以在中文目录的，为什么合在一起就不行了呢？

这个不是 ox-latex-chinese 的问题，也可能是我的配置还不够，但是希望 ox-latex-chinese 的配置中能够想办法解决这个问题。

提示如下（提示的错误不能复制完全，在下面贴图了）：
```
﻿Debugger entered--Lisp error: (error "PDF file ./simulation-note-of-2016-07.pdf wasn't produced")
  signal(error ("PDF file ./simulation-note-of-2016-07.pdf wasn't produced"))
  error("PDF file ./simulation-note-of-2016-07.pdf wasn't produced")
```

![image](https://cloud.githubusercontent.com/assets/13887263/16794605/8a00855e-490b-11e6-8188-0f3fc48b6e73.png)

**Comment by tumashu** [comment]
我这里也能够重现这个问题，原因可能是 shell-command 命令不能正确处理带有中文的参数
```
(shell-command "xelatex -interaction nonstopmode -output-directory \"./\" \"c:/Users/Administrator/Desktop/新建文件夹/test.tex\"")
```

```
! I can't find file `c:/Users/Administrator/Desktop/新建文件墿test.tex'.
```

**Comment by tumashu** [comment]
我这里也能够重现这个问题，原因可能是 shell-command 命令不能正确处理带有中文的参数
```
(shell-command "xelatex -interaction nonstopmode -output-directory \"./\" \"c:/Users/Administrator/Desktop/新建文件夹/test.tex\"")
```

```
! I can't find file `c:/Users/Administrator/Desktop/新建文件墿test.tex'.
```

**Comment by saccohuo** [comment]
这个有没有办法解决呢，或者有没有办法 walkaround 呢？

**Comment by tumashu** [comment]
暂时想不到。。。。

**Comment by saccohuo** [comment]
这个 shell-command 命令是在哪里执行的呢，如果替换为 eshell-command 是不是能作为一个 walkaround 呢？

**Comment by saccohuo** [comment]
我之前理解错了你的意思，以为你这边显示的文件名乱码了。

找了很多网页，把文件路径和文件名在 `shell-command` 中显示不乱码了。
但是重新试了一下中文目录，还是提示找不到那个文件，说明似乎显示乱码和不能识别中文目录并不是同一个问题。

现在能想到的临时办法只能是（自动实现）：导出之前把 tex 文件拷贝一份到临时目录（英文目录和英文文件名），然后导出之后，再拷贝回当前目录，接着删除临时文件和临时目录。

不过太复杂了，大文件的话还可能耽误时间，也可能会目录冲突。而且这并不是真正该解决的问题，所以还是得想最终该怎么解决。

**Comment by saccohuo** [comment]
直接执行 org 转 pdf 时候 *Org PDF LaTeX Output* buffer 里面的结果如下：
···
﻿This is XeTeX, Version 3.14159265-2.6-0.99996 (TeX Live 2016/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
! I can't find file `"d:/MyDocuments/My Knowledge/Data/shuaike945@gmail.com/Aca
demic/Projects/驴菓褩芙锇嬄妒柯柯 ⒙甭 镐 rg_Attachments/master-proposal-report.tex"'.
<*> ...痳g_Attachments/master-proposal-report.tex"
                                                  
(Press Enter to retry, or Control-Z to exit)
Please type another input file name
! Emergency stop.
<*> ...痳g_Attachments/master-proposal-report.tex"
                                                  
No pages of output.
Transcript written on .//texput.log.
···

感觉好像只是目录名和文件名的编码问题？

**Comment by tumashu** [comment]
今天想到几个可能有用的技巧，可以试试下面两种设置
```
(setq oxlc/org-latex-commands '("latexmk -xelatex -g -pdf %b.tex"))
(setq oxlc/org-latex-commands '("latexmk -xelatex -g -pdf %f"))
```

**Comment by saccohuo** [comment]
话说 org-latex-commands 这个变量使用来干嘛的啊？emacs里面这个variable没有说明。

**Comment by saccohuo** [comment]
第一个命令可以生成pdf，但是只有标题和目录名，其他所有内容（包括目录内容和正文）都消失了。

**Comment by tumashu** [comment]
用最新版的 ox-latex-chinese，测试下面两个命令，不要想当然的搞：-）
```
(setq oxlc/org-latex-commands '("latexmk -xelatex -g -pdf %b.tex"))
(setq oxlc/org-latex-commands '("latexmk -xelatex -g -pdf %f"))
```

**Comment by saccohuo** [comment]
前一个命令可以正常，后一个命令提示错误。
```
﻿Debugger entered--Lisp error: (error "PDF file ./test-normal.pdf wasn't produced")
  signal(error ("PDF file ./test-normal.pdf wasn't produced"))
  error("PDF file ./test-normal.pdf wasn't produced")
  #[(texfile &optional snippet) "\306\307!!\310!\311!\312!\203
﻿ oxlc/org-latex-compile(#[(texfile &optional snippet) "\306\307!!\310!\311!\312!\203
﻿  apply(oxlc/org-latex-compile #[(texfile &optional snippet) "\306\307!!\310!\311!\312!\203
  org-latex-compile("./test-normal.tex")
  #[(file) "\301!\207" [file org-latex-compile] 2]("./test-normal.tex")
  org-export-to-file(latex "./test-normal.tex" nil nil nil nil nil #[(file) "\301!\207" [file org-latex-compile] 2])
  org-latex-export-to-pdf(nil nil nil nil)
  (org-open-file (org-latex-export-to-pdf nil s v b))
  (if a (org-latex-export-to-pdf t s v b) (org-open-file (org-latex-export-to-pdf nil s v b)))
  (lambda (a s v b) (if a (org-latex-export-to-pdf t s v b) (org-open-file (org-latex-export-to-pdf nil s v b))))(nil nil nil nil)
  org-export-dispatch(nil)
  #<subr call-interactively>(org-export-dispatch nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> org-export-dispatch nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (org-export-dispatch nil nil))
  call-interactively(org-export-dispatch nil nil)
  command-execute(org-export-dispatch)
```

**Comment by tumashu** [comment]
中文目录可以处理吗？

**Comment by saccohuo** [comment]
可以处理的

**Comment by saccohuo** [comment]
使用新版本，在 org 文档中使用 `#+BIND:` 关键词设置变量 `org-latex-title-command` 和 `org-latex-toc-command` 来控制 LaTeX 中是否导出 title 和 toc 的方法失效。
