### ISSUE TITLE
第二次及以后使用 C-e l o 导出 pdf 不能生成目录

### ISSUE THREAD

**Issue by saccohuo** [tumashu/ox-latex-chinese#4]
第一次在 org 中使用 `C-e l o` 导出 pdf 时正常，但是此时修改 org 文件之后，重新使用 `C-e l o` 导出 pdf，pdf中的目录会消失。

环境：Windows 7 x64，emacs 24.5，org 8.2.10。

**Comment by tumashu** [comment]
这个似乎是latexmk的参数设置不当导致的吧？

**Comment by saccohuo** [comment]
这部分我没有去了解。
现在是按照前两天你给出的方案（README里面的）来设置的。

**Comment by tumashu** [comment]
READMR.md是自动生成的文件，你应该改ox-latex-chinese.el的commentary部分的注释

**Comment by saccohuo** [comment]
soga，你用的什么工具哎（虽然好像你之前说过）。
还有个问题：话说linux下，latex 可以编译中文文件名的 tex 文件吗？
