### ISSUE TITLE
求助：关于org中嵌入latex图片

### ISSUE THREAD

**Issue by QiangF** [tumashu/ox-latex-chinese#5]
大师您好，
我有一个问题好久都没解决，就是org mode导出为odt文件里嵌入latex图片。
也许您知道怎么弄。
可以分为3个小问题：
1 怎么在公式里输入中文；
2 公式如何取消编号，在导出的odt文件中给图片在右侧编号；
3 怎么把latex表格导出成图片嵌入到odt文件里面。
下面是我的一个失败的尝试。

```
#+OPTIONS: AUTHOR:nil toc:nil tex:imagemagick
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{xeCJK}
#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \xeCJKsetup{CJKmath=true}
#+LATEX_HEADER: \setCJKmainfont{WenQuanYi Micro Hei}


\begin{equation}
你好e=mc^2
\end{equation}


#+BEGIN_LATEX
\begin{table}
\begin{tabular}{ l c r }
1 & 2 & 3 \\
4 & 5 & 6 \\
\end{tabular}
#+END_LATEX
```

有空一定好好学习elisp。

**Comment by tumashu** [comment]
1 怎么在公式里输入中文；
你要测试org的latex预览功能预览产生的图片如果可以包含中文，odt的图片就可以包含中文

2 公式如何取消编号，在导出的odt文件中给图片在右侧编号
这个很简单, latex使用没编号的数学环境

3 怎么把latex表格导出成图片嵌入到odt文件里面。
暂时没有法，也许你可以了解一下org-babel latex，

**Comment by QiangF** [comment]
我用下面的设置终于可以显示中文了，但是输出的图像分辨率很低，而且还有不是公式里的关于背景色的字符："fgrgb0,0,0,bgrgb0,0,0"

    (setq org-format-latex-header
    "\\documentclass[border=0pt]{standalone}\n\\usepackage{fontspec}\n\\usepackage{xeCJK}\n\\setCJKmainfont{WenQuanYi Micro Hei}")
    (setq org-latex-create-formula-image-program 'imagemagick)
    (setq org-format-latex-options (plist-put org-format-latex-options :scale 8.0))
    (setq org-format-latex-options (plist-put org-format-latex-options :foreground 'auto))
    (setq org-format-latex-options (plist-put org-format-latex-options :background 'auto))


libreoffice 有个插件可以完美的实现latex公式的编号，org mode导出odt如果可以这样就完美了。 http://extensions.libreoffice.org/extension-center/texmaths-1

    \begin{equation}
    e=mc^{\text{你好}}
    \end{equation}

**Comment by QiangF** [comment]
I have switched to use mathtoweb.
