### ISSUE TITLE
Feature Request：添加一个设置来决定是否自动生成字体 generate-latex-fonts-setting

### ISSUE THREAD

**Issue by saccohuo** [tumashu/ox-latex-chinese#7]
使用过程中发现导出tex文件时候，在`oxlc/org-latex-default-packages-alist`和`oxlc/org-latex-packages-alist`，会自动插入被插入字体设置。如下：
```
﻿\setmainfont{Times New Roman}
\setCJKmainfont[ItalicFont={楷体}]{宋体}
\setCJKsansfont{文泉驿微米黑}
\setCJKmonofont{文泉驿微米黑}
```
是否可以添加一个选项，来设置是否开启自动设置字体的功能。因为用户通常是有可能需要自己设置字体的。
`ox-latex-chinese.el`中的467行，对`(cons (oxlc/generate-latex-fonts-setting) oxlc/org-latex-packages-alist)`加个判断吧。

**Comment by tumashu** [comment]
也许用户应该设置 oxlc/org-latex-fonts

**Comment by saccohuo** [comment]
这个选项在README中没有发现，刚看到代码里面有。
不过这样可能只适合常用默认设置的用户，如果用户对于不同的class或者不同文档有不同的字体要求，那每次改配置似乎就不太合适了。
而且org对于两种package的设置也给出了`[NO-DEFAULT-PACKAGES]`和`[NO-PACKAGES]`的选项来禁用这些这两套package，所以我还是感觉增加一下这个选项相对更符合使用习惯。
当然，要做到像org的那两种禁用方式的话，从我作为小白的视角来看，觉得可能要更麻烦一些。所以暂时增加个参数判断可以临时解决下问题。

**Comment by tumashu** [comment]
其实你和我对 ox-latex-chinese 这个包的理解是完全不同的， 我搞这个包，不是让用户依赖它，而是给新手一个基本的信心，不让他们被 org latex 中文配置吓瘫，一旦他们了解了中文设置的基本知识，他们就应该使用 oxlc/insert-configure-template 命令来生成一个自己的配置基础。维护自己的配置， ox-latex-chinese 只是一个引路人。

**Comment by tumashu** [comment]
latex 系统是非常复杂，功能也是非常强大的，要 ox-latex-chinese 满足不同用户的需求，是不可能的。

**Comment by saccohuo** [comment]
只是站的高度不同而已，我现在对elisp还是一窍不通，暂时也没有精力来系统学习。
所以依赖着你的配置搞出什么问题，也相对好解决一点。我之前自己的配置就是遇到那个编译的问题，但是我的配置跟你的不同，没法请教。换成你的配置之后，才解决的那个问题，应该在之前的issue里。

我试了一下你说的那个函数，发现生成的只是我现在针对package和class的一些而已，并不包含oxlc包里面的那一些`compile`和`export-as`之类的代码。所以这个函数对我基本没有价值，跟这个issue的问题也在一个级别。

**Comment by saccohuo** [comment]
所以通过配置package和class之类的可以解决的我勉强可以自己搞定，但是涉及比较多的lisp的跟emacs交互的部分，我还是差的比较多。
而且我觉得这个issue提到的问题并不需要做很多修改，常用的用户应该也会需要这个功能的。

**Comment by tumashu** [comment]
其实你可以 (setq oxlc/org-latex-fonts nil) 试试

**Comment by saccohuo** [comment]
可以解决我的问题，谢啦
